"""updated actual_length_of_stay column to datetime from integer, and added unique constraint to username

Revision ID: 208c84a20af6
Revises: ba5d41eb21d6
Create Date: 2023-12-19 22:19:01.959131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208c84a20af6'
down_revision = 'ba5d41eb21d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_username_constraint', ['username'])

    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.alter_column('actual_length_of_stay',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.alter_column('actual_length_of_stay',
               existing_type=sa.DateTime(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('unique_username_constraint', type_='unique')

    # ### end Alembic commands ###
