"""creating friend table

Revision ID: 50a914a9b4dc
Revises: 9b3420e9cea3
Create Date: 2023-08-16 15:24:07.466095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a914a9b4dc'
down_revision = '9b3420e9cea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friend_1_id', sa.Integer(), nullable=True),
    sa.Column('friend_2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend_1_id'], ['users.id'], name=op.f('fk_friends_friend_1_id_users')),
    sa.ForeignKeyConstraint(['friend_2_id'], ['users.id'], name=op.f('fk_friends_friend_2_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    # ### end Alembic commands ###
