"""Added image

Revision ID: 62bb26b720c6
Revises: c9e781faedcd
Create Date: 2023-04-18 15:01:28.755041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62bb26b720c6'
down_revision = 'c9e781faedcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog_parks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog_parks', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
