"""added unique  constraint for pend_friend relationship

Revision ID: 6b2a30363f3e
Revises: ba5d41eb21d6
Create Date: 2023-10-03 12:41:18.046217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2a30363f3e'
down_revision = 'ba5d41eb21d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_friendships', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_pending_friendship', ['pend_friend_1_id', 'pend_friend_2_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_friendships', schema=None) as batch_op:
        batch_op.drop_constraint('unique_pending_friendship', type_='unique')

    # ### end Alembic commands ###
