"""Models Created

Revision ID: e1b8683af596
Revises: ece3668a050c
Create Date: 2023-04-17 15:31:21.438756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1b8683af596'
down_revision = 'ece3668a050c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dog_parks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('amenities', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('breed', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_dogs_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('length_of_stay', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('dogs_id', sa.Integer(), nullable=True),
    sa.Column('dogs_id2', sa.Integer(), nullable=True),
    sa.Column('dogs_id3', sa.Integer(), nullable=True),
    sa.Column('dog_parks_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dog_parks_id'], ['dog_parks.id'], name=op.f('fk_visits_dog_parks_id_dog_parks')),
    sa.ForeignKeyConstraint(['dogs_id'], ['dogs.id'], name=op.f('fk_visits_dogs_id_dogs')),
    sa.ForeignKeyConstraint(['dogs_id2'], ['dogs.id'], name=op.f('fk_visits_dogs_id2_dogs')),
    sa.ForeignKeyConstraint(['dogs_id3'], ['dogs.id'], name=op.f('fk_visits_dogs_id3_dogs')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits')
    op.drop_table('dogs')
    op.drop_table('users')
    op.drop_table('dog_parks')
    # ### end Alembic commands ###
