"""added actual_length_of_stay to Visits

Revision ID: f6a0b624d987
Revises: 62bb26b720c6
Create Date: 2023-04-19 09:50:02.047785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a0b624d987'
down_revision = '62bb26b720c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_length_of_stay', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_column('actual_length_of_stay')

    # ### end Alembic commands ###
